# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ArticleProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ArticleProto.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x12\x41rticleProto.proto\"/\n\x0b\x41rticleList\x12 \n\x08\x61rticles\x18\x01 \x03(\x0b\x32\x0e.ArticleDetail\"{\n\rArticleDetail\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x10\n\x08imageUrl\x18\x04 \x01(\t\x12\x0c\n\x04time\x18\x05 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x06 \x01(\t\x12\x0c\n\x04\x62ody\x18\x07 \x01(\tb\x06proto3')
)




_ARTICLELIST = _descriptor.Descriptor(
  name='ArticleList',
  full_name='ArticleList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='articles', full_name='ArticleList.articles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=69,
)


_ARTICLEDETAIL = _descriptor.Descriptor(
  name='ArticleDetail',
  full_name='ArticleDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='ArticleDetail.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='ArticleDetail.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='ArticleDetail.source', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageUrl', full_name='ArticleDetail.imageUrl', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='ArticleDetail.time', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='category', full_name='ArticleDetail.category', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='ArticleDetail.body', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=194,
)

_ARTICLELIST.fields_by_name['articles'].message_type = _ARTICLEDETAIL
DESCRIPTOR.message_types_by_name['ArticleList'] = _ARTICLELIST
DESCRIPTOR.message_types_by_name['ArticleDetail'] = _ARTICLEDETAIL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArticleList = _reflection.GeneratedProtocolMessageType('ArticleList', (_message.Message,), dict(
  DESCRIPTOR = _ARTICLELIST,
  __module__ = 'ArticleProto_pb2'
  # @@protoc_insertion_point(class_scope:ArticleList)
  ))
_sym_db.RegisterMessage(ArticleList)

ArticleDetail = _reflection.GeneratedProtocolMessageType('ArticleDetail', (_message.Message,), dict(
  DESCRIPTOR = _ARTICLEDETAIL,
  __module__ = 'ArticleProto_pb2'
  # @@protoc_insertion_point(class_scope:ArticleDetail)
  ))
_sym_db.RegisterMessage(ArticleDetail)


# @@protoc_insertion_point(module_scope)
