// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ArticleProto.proto

public final class ArticleProto {
  private ArticleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ArticleListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ArticleList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ArticleDetail articles = 1;</code>
     */
    java.util.List<ArticleProto.ArticleDetail> 
        getArticlesList();
    /**
     * <code>repeated .ArticleDetail articles = 1;</code>
     */
    ArticleProto.ArticleDetail getArticles(int index);
    /**
     * <code>repeated .ArticleDetail articles = 1;</code>
     */
    int getArticlesCount();
    /**
     * <code>repeated .ArticleDetail articles = 1;</code>
     */
    java.util.List<? extends ArticleProto.ArticleDetailOrBuilder> 
        getArticlesOrBuilderList();
    /**
     * <code>repeated .ArticleDetail articles = 1;</code>
     */
    ArticleProto.ArticleDetailOrBuilder getArticlesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ArticleList}
   */
  public  static final class ArticleList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ArticleList)
      ArticleListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ArticleList.newBuilder() to construct.
    private ArticleList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ArticleList() {
      articles_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ArticleList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                articles_ = new java.util.ArrayList<ArticleProto.ArticleDetail>();
                mutable_bitField0_ |= 0x00000001;
              }
              articles_.add(
                  input.readMessage(ArticleProto.ArticleDetail.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          articles_ = java.util.Collections.unmodifiableList(articles_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ArticleProto.internal_static_ArticleList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ArticleProto.internal_static_ArticleList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ArticleProto.ArticleList.class, ArticleProto.ArticleList.Builder.class);
    }

    public static final int ARTICLES_FIELD_NUMBER = 1;
    private java.util.List<ArticleProto.ArticleDetail> articles_;
    /**
     * <code>repeated .ArticleDetail articles = 1;</code>
     */
    public java.util.List<ArticleProto.ArticleDetail> getArticlesList() {
      return articles_;
    }
    /**
     * <code>repeated .ArticleDetail articles = 1;</code>
     */
    public java.util.List<? extends ArticleProto.ArticleDetailOrBuilder> 
        getArticlesOrBuilderList() {
      return articles_;
    }
    /**
     * <code>repeated .ArticleDetail articles = 1;</code>
     */
    public int getArticlesCount() {
      return articles_.size();
    }
    /**
     * <code>repeated .ArticleDetail articles = 1;</code>
     */
    public ArticleProto.ArticleDetail getArticles(int index) {
      return articles_.get(index);
    }
    /**
     * <code>repeated .ArticleDetail articles = 1;</code>
     */
    public ArticleProto.ArticleDetailOrBuilder getArticlesOrBuilder(
        int index) {
      return articles_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < articles_.size(); i++) {
        output.writeMessage(1, articles_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < articles_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, articles_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ArticleProto.ArticleList)) {
        return super.equals(obj);
      }
      ArticleProto.ArticleList other = (ArticleProto.ArticleList) obj;

      boolean result = true;
      result = result && getArticlesList()
          .equals(other.getArticlesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getArticlesCount() > 0) {
        hash = (37 * hash) + ARTICLES_FIELD_NUMBER;
        hash = (53 * hash) + getArticlesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ArticleProto.ArticleList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ArticleProto.ArticleList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ArticleProto.ArticleList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ArticleProto.ArticleList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ArticleProto.ArticleList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ArticleProto.ArticleList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ArticleProto.ArticleList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ArticleProto.ArticleList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ArticleProto.ArticleList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ArticleProto.ArticleList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ArticleProto.ArticleList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ArticleProto.ArticleList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ArticleProto.ArticleList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ArticleList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ArticleList)
        ArticleProto.ArticleListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ArticleProto.internal_static_ArticleList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ArticleProto.internal_static_ArticleList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ArticleProto.ArticleList.class, ArticleProto.ArticleList.Builder.class);
      }

      // Construct using ArticleProto.ArticleList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getArticlesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (articlesBuilder_ == null) {
          articles_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          articlesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ArticleProto.internal_static_ArticleList_descriptor;
      }

      public ArticleProto.ArticleList getDefaultInstanceForType() {
        return ArticleProto.ArticleList.getDefaultInstance();
      }

      public ArticleProto.ArticleList build() {
        ArticleProto.ArticleList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ArticleProto.ArticleList buildPartial() {
        ArticleProto.ArticleList result = new ArticleProto.ArticleList(this);
        int from_bitField0_ = bitField0_;
        if (articlesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            articles_ = java.util.Collections.unmodifiableList(articles_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.articles_ = articles_;
        } else {
          result.articles_ = articlesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ArticleProto.ArticleList) {
          return mergeFrom((ArticleProto.ArticleList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ArticleProto.ArticleList other) {
        if (other == ArticleProto.ArticleList.getDefaultInstance()) return this;
        if (articlesBuilder_ == null) {
          if (!other.articles_.isEmpty()) {
            if (articles_.isEmpty()) {
              articles_ = other.articles_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureArticlesIsMutable();
              articles_.addAll(other.articles_);
            }
            onChanged();
          }
        } else {
          if (!other.articles_.isEmpty()) {
            if (articlesBuilder_.isEmpty()) {
              articlesBuilder_.dispose();
              articlesBuilder_ = null;
              articles_ = other.articles_;
              bitField0_ = (bitField0_ & ~0x00000001);
              articlesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getArticlesFieldBuilder() : null;
            } else {
              articlesBuilder_.addAllMessages(other.articles_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ArticleProto.ArticleList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ArticleProto.ArticleList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ArticleProto.ArticleDetail> articles_ =
        java.util.Collections.emptyList();
      private void ensureArticlesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          articles_ = new java.util.ArrayList<ArticleProto.ArticleDetail>(articles_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ArticleProto.ArticleDetail, ArticleProto.ArticleDetail.Builder, ArticleProto.ArticleDetailOrBuilder> articlesBuilder_;

      /**
       * <code>repeated .ArticleDetail articles = 1;</code>
       */
      public java.util.List<ArticleProto.ArticleDetail> getArticlesList() {
        if (articlesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(articles_);
        } else {
          return articlesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ArticleDetail articles = 1;</code>
       */
      public int getArticlesCount() {
        if (articlesBuilder_ == null) {
          return articles_.size();
        } else {
          return articlesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ArticleDetail articles = 1;</code>
       */
      public ArticleProto.ArticleDetail getArticles(int index) {
        if (articlesBuilder_ == null) {
          return articles_.get(index);
        } else {
          return articlesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ArticleDetail articles = 1;</code>
       */
      public Builder setArticles(
          int index, ArticleProto.ArticleDetail value) {
        if (articlesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArticlesIsMutable();
          articles_.set(index, value);
          onChanged();
        } else {
          articlesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ArticleDetail articles = 1;</code>
       */
      public Builder setArticles(
          int index, ArticleProto.ArticleDetail.Builder builderForValue) {
        if (articlesBuilder_ == null) {
          ensureArticlesIsMutable();
          articles_.set(index, builderForValue.build());
          onChanged();
        } else {
          articlesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ArticleDetail articles = 1;</code>
       */
      public Builder addArticles(ArticleProto.ArticleDetail value) {
        if (articlesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArticlesIsMutable();
          articles_.add(value);
          onChanged();
        } else {
          articlesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ArticleDetail articles = 1;</code>
       */
      public Builder addArticles(
          int index, ArticleProto.ArticleDetail value) {
        if (articlesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArticlesIsMutable();
          articles_.add(index, value);
          onChanged();
        } else {
          articlesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ArticleDetail articles = 1;</code>
       */
      public Builder addArticles(
          ArticleProto.ArticleDetail.Builder builderForValue) {
        if (articlesBuilder_ == null) {
          ensureArticlesIsMutable();
          articles_.add(builderForValue.build());
          onChanged();
        } else {
          articlesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ArticleDetail articles = 1;</code>
       */
      public Builder addArticles(
          int index, ArticleProto.ArticleDetail.Builder builderForValue) {
        if (articlesBuilder_ == null) {
          ensureArticlesIsMutable();
          articles_.add(index, builderForValue.build());
          onChanged();
        } else {
          articlesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ArticleDetail articles = 1;</code>
       */
      public Builder addAllArticles(
          java.lang.Iterable<? extends ArticleProto.ArticleDetail> values) {
        if (articlesBuilder_ == null) {
          ensureArticlesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, articles_);
          onChanged();
        } else {
          articlesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ArticleDetail articles = 1;</code>
       */
      public Builder clearArticles() {
        if (articlesBuilder_ == null) {
          articles_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          articlesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ArticleDetail articles = 1;</code>
       */
      public Builder removeArticles(int index) {
        if (articlesBuilder_ == null) {
          ensureArticlesIsMutable();
          articles_.remove(index);
          onChanged();
        } else {
          articlesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ArticleDetail articles = 1;</code>
       */
      public ArticleProto.ArticleDetail.Builder getArticlesBuilder(
          int index) {
        return getArticlesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ArticleDetail articles = 1;</code>
       */
      public ArticleProto.ArticleDetailOrBuilder getArticlesOrBuilder(
          int index) {
        if (articlesBuilder_ == null) {
          return articles_.get(index);  } else {
          return articlesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ArticleDetail articles = 1;</code>
       */
      public java.util.List<? extends ArticleProto.ArticleDetailOrBuilder> 
           getArticlesOrBuilderList() {
        if (articlesBuilder_ != null) {
          return articlesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(articles_);
        }
      }
      /**
       * <code>repeated .ArticleDetail articles = 1;</code>
       */
      public ArticleProto.ArticleDetail.Builder addArticlesBuilder() {
        return getArticlesFieldBuilder().addBuilder(
            ArticleProto.ArticleDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .ArticleDetail articles = 1;</code>
       */
      public ArticleProto.ArticleDetail.Builder addArticlesBuilder(
          int index) {
        return getArticlesFieldBuilder().addBuilder(
            index, ArticleProto.ArticleDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .ArticleDetail articles = 1;</code>
       */
      public java.util.List<ArticleProto.ArticleDetail.Builder> 
           getArticlesBuilderList() {
        return getArticlesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ArticleProto.ArticleDetail, ArticleProto.ArticleDetail.Builder, ArticleProto.ArticleDetailOrBuilder> 
          getArticlesFieldBuilder() {
        if (articlesBuilder_ == null) {
          articlesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ArticleProto.ArticleDetail, ArticleProto.ArticleDetail.Builder, ArticleProto.ArticleDetailOrBuilder>(
                  articles_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          articles_ = null;
        }
        return articlesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ArticleList)
    }

    // @@protoc_insertion_point(class_scope:ArticleList)
    private static final ArticleProto.ArticleList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ArticleProto.ArticleList();
    }

    public static ArticleProto.ArticleList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ArticleList>
        PARSER = new com.google.protobuf.AbstractParser<ArticleList>() {
      public ArticleList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ArticleList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ArticleList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ArticleList> getParserForType() {
      return PARSER;
    }

    public ArticleProto.ArticleList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ArticleDetailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ArticleDetail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uri = 1;</code>
     */
    java.lang.String getUri();
    /**
     * <code>string uri = 1;</code>
     */
    com.google.protobuf.ByteString
        getUriBytes();

    /**
     * <code>string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string source = 3;</code>
     */
    java.lang.String getSource();
    /**
     * <code>string source = 3;</code>
     */
    com.google.protobuf.ByteString
        getSourceBytes();

    /**
     * <code>string imageUrl = 4;</code>
     */
    java.lang.String getImageUrl();
    /**
     * <code>string imageUrl = 4;</code>
     */
    com.google.protobuf.ByteString
        getImageUrlBytes();

    /**
     * <code>string time = 5;</code>
     */
    java.lang.String getTime();
    /**
     * <code>string time = 5;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <code>string category = 6;</code>
     */
    java.lang.String getCategory();
    /**
     * <code>string category = 6;</code>
     */
    com.google.protobuf.ByteString
        getCategoryBytes();

    /**
     * <code>string body = 7;</code>
     */
    java.lang.String getBody();
    /**
     * <code>string body = 7;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();
  }
  /**
   * Protobuf type {@code ArticleDetail}
   */
  public  static final class ArticleDetail extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ArticleDetail)
      ArticleDetailOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ArticleDetail.newBuilder() to construct.
    private ArticleDetail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ArticleDetail() {
      uri_ = "";
      title_ = "";
      source_ = "";
      imageUrl_ = "";
      time_ = "";
      category_ = "";
      body_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ArticleDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uri_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              source_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              imageUrl_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              time_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              category_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              body_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ArticleProto.internal_static_ArticleDetail_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ArticleProto.internal_static_ArticleDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ArticleProto.ArticleDetail.class, ArticleProto.ArticleDetail.Builder.class);
    }

    public static final int URI_FIELD_NUMBER = 1;
    private volatile java.lang.Object uri_;
    /**
     * <code>string uri = 1;</code>
     */
    public java.lang.String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uri_ = s;
        return s;
      }
    }
    /**
     * <code>string uri = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCE_FIELD_NUMBER = 3;
    private volatile java.lang.Object source_;
    /**
     * <code>string source = 3;</code>
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        source_ = s;
        return s;
      }
    }
    /**
     * <code>string source = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGEURL_FIELD_NUMBER = 4;
    private volatile java.lang.Object imageUrl_;
    /**
     * <code>string imageUrl = 4;</code>
     */
    public java.lang.String getImageUrl() {
      java.lang.Object ref = imageUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string imageUrl = 4;</code>
     */
    public com.google.protobuf.ByteString
        getImageUrlBytes() {
      java.lang.Object ref = imageUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 5;
    private volatile java.lang.Object time_;
    /**
     * <code>string time = 5;</code>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        time_ = s;
        return s;
      }
    }
    /**
     * <code>string time = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CATEGORY_FIELD_NUMBER = 6;
    private volatile java.lang.Object category_;
    /**
     * <code>string category = 6;</code>
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      }
    }
    /**
     * <code>string category = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 7;
    private volatile java.lang.Object body_;
    /**
     * <code>string body = 7;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <code>string body = 7;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUriBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uri_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (!getSourceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, source_);
      }
      if (!getImageUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, imageUrl_);
      }
      if (!getTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, time_);
      }
      if (!getCategoryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, category_);
      }
      if (!getBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, body_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUriBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uri_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (!getSourceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, source_);
      }
      if (!getImageUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, imageUrl_);
      }
      if (!getTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, time_);
      }
      if (!getCategoryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, category_);
      }
      if (!getBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ArticleProto.ArticleDetail)) {
        return super.equals(obj);
      }
      ArticleProto.ArticleDetail other = (ArticleProto.ArticleDetail) obj;

      boolean result = true;
      result = result && getUri()
          .equals(other.getUri());
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && getSource()
          .equals(other.getSource());
      result = result && getImageUrl()
          .equals(other.getImageUrl());
      result = result && getTime()
          .equals(other.getTime());
      result = result && getCategory()
          .equals(other.getCategory());
      result = result && getBody()
          .equals(other.getBody());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + URI_FIELD_NUMBER;
      hash = (53 * hash) + getUri().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSource().hashCode();
      hash = (37 * hash) + IMAGEURL_FIELD_NUMBER;
      hash = (53 * hash) + getImageUrl().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getCategory().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ArticleProto.ArticleDetail parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ArticleProto.ArticleDetail parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ArticleProto.ArticleDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ArticleProto.ArticleDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ArticleProto.ArticleDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ArticleProto.ArticleDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ArticleProto.ArticleDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ArticleProto.ArticleDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ArticleProto.ArticleDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ArticleProto.ArticleDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ArticleProto.ArticleDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ArticleProto.ArticleDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ArticleProto.ArticleDetail prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ArticleDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ArticleDetail)
        ArticleProto.ArticleDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ArticleProto.internal_static_ArticleDetail_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ArticleProto.internal_static_ArticleDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ArticleProto.ArticleDetail.class, ArticleProto.ArticleDetail.Builder.class);
      }

      // Construct using ArticleProto.ArticleDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uri_ = "";

        title_ = "";

        source_ = "";

        imageUrl_ = "";

        time_ = "";

        category_ = "";

        body_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ArticleProto.internal_static_ArticleDetail_descriptor;
      }

      public ArticleProto.ArticleDetail getDefaultInstanceForType() {
        return ArticleProto.ArticleDetail.getDefaultInstance();
      }

      public ArticleProto.ArticleDetail build() {
        ArticleProto.ArticleDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ArticleProto.ArticleDetail buildPartial() {
        ArticleProto.ArticleDetail result = new ArticleProto.ArticleDetail(this);
        result.uri_ = uri_;
        result.title_ = title_;
        result.source_ = source_;
        result.imageUrl_ = imageUrl_;
        result.time_ = time_;
        result.category_ = category_;
        result.body_ = body_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ArticleProto.ArticleDetail) {
          return mergeFrom((ArticleProto.ArticleDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ArticleProto.ArticleDetail other) {
        if (other == ArticleProto.ArticleDetail.getDefaultInstance()) return this;
        if (!other.getUri().isEmpty()) {
          uri_ = other.uri_;
          onChanged();
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getSource().isEmpty()) {
          source_ = other.source_;
          onChanged();
        }
        if (!other.getImageUrl().isEmpty()) {
          imageUrl_ = other.imageUrl_;
          onChanged();
        }
        if (!other.getTime().isEmpty()) {
          time_ = other.time_;
          onChanged();
        }
        if (!other.getCategory().isEmpty()) {
          category_ = other.category_;
          onChanged();
        }
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ArticleProto.ArticleDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ArticleProto.ArticleDetail) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uri_ = "";
      /**
       * <code>string uri = 1;</code>
       */
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uri = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uri = 1;</code>
       */
      public Builder setUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uri = 1;</code>
       */
      public Builder clearUri() {
        
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      /**
       * <code>string uri = 1;</code>
       */
      public Builder setUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uri_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object source_ = "";
      /**
       * <code>string source = 3;</code>
       */
      public java.lang.String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          source_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string source = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        java.lang.Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string source = 3;</code>
       */
      public Builder setSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string source = 3;</code>
       */
      public Builder clearSource() {
        
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      /**
       * <code>string source = 3;</code>
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        source_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object imageUrl_ = "";
      /**
       * <code>string imageUrl = 4;</code>
       */
      public java.lang.String getImageUrl() {
        java.lang.Object ref = imageUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imageUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string imageUrl = 4;</code>
       */
      public com.google.protobuf.ByteString
          getImageUrlBytes() {
        java.lang.Object ref = imageUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imageUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string imageUrl = 4;</code>
       */
      public Builder setImageUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string imageUrl = 4;</code>
       */
      public Builder clearImageUrl() {
        
        imageUrl_ = getDefaultInstance().getImageUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string imageUrl = 4;</code>
       */
      public Builder setImageUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imageUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object time_ = "";
      /**
       * <code>string time = 5;</code>
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string time = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string time = 5;</code>
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string time = 5;</code>
       */
      public Builder clearTime() {
        
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>string time = 5;</code>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        time_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object category_ = "";
      /**
       * <code>string category = 6;</code>
       */
      public java.lang.String getCategory() {
        java.lang.Object ref = category_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          category_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string category = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCategoryBytes() {
        java.lang.Object ref = category_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          category_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string category = 6;</code>
       */
      public Builder setCategory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string category = 6;</code>
       */
      public Builder clearCategory() {
        
        category_ = getDefaultInstance().getCategory();
        onChanged();
        return this;
      }
      /**
       * <code>string category = 6;</code>
       */
      public Builder setCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        category_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <code>string body = 7;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string body = 7;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string body = 7;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string body = 7;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>string body = 7;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        body_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ArticleDetail)
    }

    // @@protoc_insertion_point(class_scope:ArticleDetail)
    private static final ArticleProto.ArticleDetail DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ArticleProto.ArticleDetail();
    }

    public static ArticleProto.ArticleDetail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ArticleDetail>
        PARSER = new com.google.protobuf.AbstractParser<ArticleDetail>() {
      public ArticleDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ArticleDetail(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ArticleDetail> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ArticleDetail> getParserForType() {
      return PARSER;
    }

    public ArticleProto.ArticleDetail getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ArticleList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ArticleList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ArticleDetail_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ArticleDetail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ArticleProto.proto\"/\n\013ArticleList\022 \n\010a" +
      "rticles\030\001 \003(\0132\016.ArticleDetail\"{\n\rArticle" +
      "Detail\022\013\n\003uri\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\016\n\006so" +
      "urce\030\003 \001(\t\022\020\n\010imageUrl\030\004 \001(\t\022\014\n\004time\030\005 \001" +
      "(\t\022\020\n\010category\030\006 \001(\t\022\014\n\004body\030\007 \001(\tb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ArticleList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ArticleList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ArticleList_descriptor,
        new java.lang.String[] { "Articles", });
    internal_static_ArticleDetail_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ArticleDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ArticleDetail_descriptor,
        new java.lang.String[] { "Uri", "Title", "Source", "ImageUrl", "Time", "Category", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
