# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WordDetailProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WordDetailProto.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x15WordDetailProto.proto\"+\n\x08WordList\x12\x1f\n\nwordDetail\x18\x01 \x03(\x0b\x32\x0b.WordDetail\"\x93\x02\n\nWordDetail\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x1b\n\x08relation\x18\x02 \x01(\x0b\x32\t.Relation\x12\x17\n\x08pron_bri\x18\x03 \x01(\x0b\x32\x05.Pron\x12\x17\n\x08pron_ame\x18\x04 \x01(\x0b\x32\x05.Pron\x12\x0f\n\x07\x63ollins\x18\x05 \x01(\x05\x12\x0b\n\x03tag\x18\x06 \x01(\t\x12\x10\n\x08tag_flag\x18\x07 \x03(\x08\x12\x0b\n\x03\x62nc\x18\x08 \x01(\x05\x12\x0b\n\x03\x66rq\x18\t \x01(\x05\x12\x13\n\x0b\x65ng_explain\x18\n \x01(\t\x12\x19\n\x07\x65xplain\x18\x0b \x03(\x0b\x32\x08.Explain\x12\x1b\n\x08sentence\x18\x0c \x03(\x0b\x32\t.Sentence\x12\x11\n\texchanges\x18\r \x03(\t\"4\n\x08Relation\x12\x12\n\nplain_word\x18\x01 \x01(\t\x12\x14\n\x0crelationship\x18\x02 \x01(\t\"\x1f\n\x04Pron\x12\n\n\x02ps\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"\'\n\x07\x45xplain\x12\x0b\n\x03pos\x18\x01 \x01(\t\x12\x0f\n\x07meaning\x18\x02 \x01(\t\"4\n\x08Sentence\x12\x0b\n\x03\x65ng\x18\x01 \x01(\t\x12\x0b\n\x03\x63hn\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\tb\x06proto3')
)




_WORDLIST = _descriptor.Descriptor(
  name='WordList',
  full_name='WordList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wordDetail', full_name='WordList.wordDetail', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=68,
)


_WORDDETAIL = _descriptor.Descriptor(
  name='WordDetail',
  full_name='WordDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='WordDetail.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relation', full_name='WordDetail.relation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pron_bri', full_name='WordDetail.pron_bri', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pron_ame', full_name='WordDetail.pron_ame', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collins', full_name='WordDetail.collins', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='WordDetail.tag', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag_flag', full_name='WordDetail.tag_flag', index=6,
      number=7, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bnc', full_name='WordDetail.bnc', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frq', full_name='WordDetail.frq', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eng_explain', full_name='WordDetail.eng_explain', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='explain', full_name='WordDetail.explain', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sentence', full_name='WordDetail.sentence', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchanges', full_name='WordDetail.exchanges', index=12,
      number=13, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=346,
)


_RELATION = _descriptor.Descriptor(
  name='Relation',
  full_name='Relation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='plain_word', full_name='Relation.plain_word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relationship', full_name='Relation.relationship', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=400,
)


_PRON = _descriptor.Descriptor(
  name='Pron',
  full_name='Pron',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ps', full_name='Pron.ps', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='Pron.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=433,
)


_EXPLAIN = _descriptor.Descriptor(
  name='Explain',
  full_name='Explain',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='Explain.pos', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meaning', full_name='Explain.meaning', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=474,
)


_SENTENCE = _descriptor.Descriptor(
  name='Sentence',
  full_name='Sentence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eng', full_name='Sentence.eng', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chn', full_name='Sentence.chn', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='Sentence.source', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=476,
  serialized_end=528,
)

_WORDLIST.fields_by_name['wordDetail'].message_type = _WORDDETAIL
_WORDDETAIL.fields_by_name['relation'].message_type = _RELATION
_WORDDETAIL.fields_by_name['pron_bri'].message_type = _PRON
_WORDDETAIL.fields_by_name['pron_ame'].message_type = _PRON
_WORDDETAIL.fields_by_name['explain'].message_type = _EXPLAIN
_WORDDETAIL.fields_by_name['sentence'].message_type = _SENTENCE
DESCRIPTOR.message_types_by_name['WordList'] = _WORDLIST
DESCRIPTOR.message_types_by_name['WordDetail'] = _WORDDETAIL
DESCRIPTOR.message_types_by_name['Relation'] = _RELATION
DESCRIPTOR.message_types_by_name['Pron'] = _PRON
DESCRIPTOR.message_types_by_name['Explain'] = _EXPLAIN
DESCRIPTOR.message_types_by_name['Sentence'] = _SENTENCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WordList = _reflection.GeneratedProtocolMessageType('WordList', (_message.Message,), dict(
  DESCRIPTOR = _WORDLIST,
  __module__ = 'WordDetailProto_pb2'
  # @@protoc_insertion_point(class_scope:WordList)
  ))
_sym_db.RegisterMessage(WordList)

WordDetail = _reflection.GeneratedProtocolMessageType('WordDetail', (_message.Message,), dict(
  DESCRIPTOR = _WORDDETAIL,
  __module__ = 'WordDetailProto_pb2'
  # @@protoc_insertion_point(class_scope:WordDetail)
  ))
_sym_db.RegisterMessage(WordDetail)

Relation = _reflection.GeneratedProtocolMessageType('Relation', (_message.Message,), dict(
  DESCRIPTOR = _RELATION,
  __module__ = 'WordDetailProto_pb2'
  # @@protoc_insertion_point(class_scope:Relation)
  ))
_sym_db.RegisterMessage(Relation)

Pron = _reflection.GeneratedProtocolMessageType('Pron', (_message.Message,), dict(
  DESCRIPTOR = _PRON,
  __module__ = 'WordDetailProto_pb2'
  # @@protoc_insertion_point(class_scope:Pron)
  ))
_sym_db.RegisterMessage(Pron)

Explain = _reflection.GeneratedProtocolMessageType('Explain', (_message.Message,), dict(
  DESCRIPTOR = _EXPLAIN,
  __module__ = 'WordDetailProto_pb2'
  # @@protoc_insertion_point(class_scope:Explain)
  ))
_sym_db.RegisterMessage(Explain)

Sentence = _reflection.GeneratedProtocolMessageType('Sentence', (_message.Message,), dict(
  DESCRIPTOR = _SENTENCE,
  __module__ = 'WordDetailProto_pb2'
  # @@protoc_insertion_point(class_scope:Sentence)
  ))
_sym_db.RegisterMessage(Sentence)


# @@protoc_insertion_point(module_scope)
